server.port=8080
random.service.url=https://node-service:5000/plusone

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://mysql-service:3306/mysql
spring.datasource.username=${DB_USERNAME:defaultUsername}
spring.datasource.password=${DB_PASSWORD:defaultPassword}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect

# Actuator Configuration
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
management.security.enabled=true

